micronaut:
  application:
    name: usAdvice
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
