micronaut:
  application:
    name: usAdvice
  server:
    port: ${APPLICATION_PORT:9001}
    cors:
      enabled: true
  executors:
    io:
      type: fixed
      nThreads: 15
---
mongodb:
  database: htd-db
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
  options:
    maxConnectionIdleTime: 10000
    readConcern: majority
---
endpoints:
  health:
    enabled: true
    sensitive: false
  routes:
    enabled: true
    sensitive: false
---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
---
jackson:
  serialization:
    indentOutput: true
  time-zone: "America/Lima"
  locale: es_PE
